name: lofilog
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  url_launcher: ^6.3.0
  intl: ^0.19.0 # (Versi bisa beda, tapi ini aman)
  audioplayers: ^6.0.0 # (Versi bisa beda, tapi ini aman)
  table_calendar: ^3.1.2
  provider: ^6.1.2
  sqflite: ^2.3.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Mengaktifkan folder assets/images/
  assets:
    - assets/images/
    - assets/sounds/

  # Font kustom kamu
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700
    - family: Share Tech Mono
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf

# Konfigurasi untuk logo di luar aplikasi
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_launcher.png"
  adaptive_icon_background: "#0A0A12"
  adaptive_icon_foreground: "assets/images/logo_launcher.png"